create table LOLEVEL(LOLEVEL VARCHAR2(30),NUM NUMBER NOT NULL,
CONSTRAINT PRIM23 PRIMARY KEY(LOLEVEL),
CONSTRAINT PRIM24 CHECK((lolevel,num) in (('Familiarity',1),('Usage',2),('Assessment',3))));

create table KA(KACODE VARCHAR2(5),kaname VARCHAR2(50) NOT NULL,
CONSTRAINT PRIM1 PRIMARY KEY(kacode));


CREATE TABLE ku(KUID NUMBER,KU VARCHAR2(200) NOT NULL,ka VARCHAR2(5) NOT NULL,mintier1 float NOT NULL,mintier2 float NOT NULL,
constraint PRIM2 primary key(KUID),
constraint prim3 foreign key(KA) references KA(KACODE) );

create table LO(LONO NUMBER NOT NULL,LO VARCHAR2(500) NOT NULL,TIER NUMBER NOT NULL,LOLEVEL VARCHAR2(30) NOT NULL,kuid NUMBER NOT NULL,
CONSTRAINT PRIM4 PRIMARY KEY(kuid,lono),
constraint prim5 foreign key(KUID) references KU(KUID) ,
CONSTRAINT PRIM6 CHECK(TIER IN (1,2,3)),
CONSTRAINT PRIM7 foreign key(lolevel) references LOLEVEL(LOLEVEL));

CREATE TABLE COURSES (COURSEID VARCHAR2(50),COURSENAME VARCHAR2(200) NOT NULL,coursedesc varchar2(800) NOT NULL,
CONSTRAINT PRIM8 PRIMARY KEY(COURSEID));

CREATE TABLE DEGREES (DEGCODE VARCHAR2(30),DEGNAME VARCHAR2(200) NOT NULL,
CONSTRAINT PRIM9 PRIMARY KEY(DEGCODE));

CREATE TABLE NOCOURSESREQ(DEGCODE VARCHAR2(30) NOT NULL,OPTIONS NUMBER NOT NULL,NOCOURSESREQ NUMBER NOT NULL,
CONSTRAINT PRIM10 PRIMARY KEY(DEGCODE,OPTIONS),
CONSTRAINT PRIM11 FOREIGN KEY(DEGCODE) REFERENCES DEGREES(DEGCODE));

CREATE TABLE DEGREQS(DEGCODE VARCHAR2(30) NOT NULL,COURSEID VARCHAR2(50) NOT NULL,OPTIONS NUMBER NOT NULL,
CONSTRAINT PRIM12 PRIMARY KEY(DEGCODE,COURSEID),
CONSTRAINT PRIM13 FOREIGN KEY(DEGCODE) REFERENCES DEGREES(DEGCODE) ,
CONSTRAINT PRIM14 FOREIGN KEY(COURSEID) REFERENCES COURSES(COURSEID) ,
CONSTRAINT PRIM15 FOREIGN KEY(DEGCODE,OPTIONS) REFERENCES NOCOURSESREQ(DEGCODE,OPTIONS) );

CREATE TABLE COURSES_KUTAUGHT(COURSEID VARCHAR2(50) not null,KUID NUMBER not null,TIER1HRS FLOAT not null,TIER2HRS FLOAT not null,
CONSTRAINT PRIM16 PRIMARY KEY(COURSEID,KUID),
CONSTRAINT PRIM17 FOREIGN KEY(COURSEID) REFERENCES COURSES(COURSEID),
CONSTRAINT PRIM18 FOREIGN KEY(KUID) REFERENCES KU(KUID));

CREATE TABLE COURSES_INFO(COURSEID VARCHAR2(50) not null,kuid number not null,LONO NUMBER not null,LOLEVEL VARCHAR2(30) not null,
CONSTRAINT PRIM19 PRIMARY KEY(COURSEID,KUID,LONO),
CONSTRAINT PRIM20 FOREIGN KEY(KUID,LONO) REFERENCES LO(KUID,LONO) ,
CONSTRAINT PRIM21 FOREIGN KEY(COURSEID,KUID) REFERENCES COURSES_KUTAUGHT(COURSEID,KUID) ,
CONSTRAINT PRIM22 foreign key(lolevel) references LOLEVEL(LOLEVEL));



commit;